# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  - name: HOME
    url: /#top
    weight: 10
  - name: SOLUCIONES
    url: /#solutions
    weight: 20
  - name: PUBLICACIONES
    url: /#publications
    weight: 30
  - name: CONTACTO
    url: /#contact
    weight: 40
#    hasChildren: true
#  - parent: Resources
    # name: CONTACTO
    # url: blog/
