# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/


custom_css: "css/custom.css"

# Appearance
appearance:
  mode: light
  color: indigo


# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: 'SISTECMA'
    description: 'Sistecma simplifies access, integration, and scalability of AI in your business'
    twitter: 'GetResearchDev'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: "navbar" # navbar
    align: "center"
    fixed_to_top: true
    logo:
      text: "SISTECMA"
      # Logo filename in `assets/media/` folder
      filename: "sistecma.svg"
    button:
      enable: false
      text: "Get Started"
      url: "https://hugoblox.com/templates/"
    show_search: true
    show_theme_chooser: true  

# Site footer
footer:
  copyright:
    notice: '© {year} Sistecma'  

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
